/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudioIndexRouteImport } from './routes/studio.index'
import { Route as StudioNewRouteImport } from './routes/studio.new'
import { Route as StudioCIdRouteImport } from './routes/studio.c.$id'
import { Route as StudioCIdIndexRouteImport } from './routes/studio.c.$id.index'
import { Route as StudioCIdVVariantIdRouteImport } from './routes/studio.c.$id.v.$variantId'

const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioIndexRoute = StudioIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudioRoute,
} as any)
const StudioNewRoute = StudioNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => StudioRoute,
} as any)
const StudioCIdRoute = StudioCIdRouteImport.update({
  id: '/c/$id',
  path: '/c/$id',
  getParentRoute: () => StudioRoute,
} as any)
const StudioCIdIndexRoute = StudioCIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudioCIdRoute,
} as any)
const StudioCIdVVariantIdRoute = StudioCIdVVariantIdRouteImport.update({
  id: '/v/$variantId',
  path: '/v/$variantId',
  getParentRoute: () => StudioCIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/studio': typeof StudioRouteWithChildren
  '/studio/new': typeof StudioNewRoute
  '/studio/': typeof StudioIndexRoute
  '/studio/c/$id': typeof StudioCIdRouteWithChildren
  '/studio/c/$id/': typeof StudioCIdIndexRoute
  '/studio/c/$id/v/$variantId': typeof StudioCIdVVariantIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/studio/new': typeof StudioNewRoute
  '/studio': typeof StudioIndexRoute
  '/studio/c/$id': typeof StudioCIdIndexRoute
  '/studio/c/$id/v/$variantId': typeof StudioCIdVVariantIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/studio': typeof StudioRouteWithChildren
  '/studio/new': typeof StudioNewRoute
  '/studio/': typeof StudioIndexRoute
  '/studio/c/$id': typeof StudioCIdRouteWithChildren
  '/studio/c/$id/': typeof StudioCIdIndexRoute
  '/studio/c/$id/v/$variantId': typeof StudioCIdVVariantIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/studio'
    | '/studio/new'
    | '/studio/'
    | '/studio/c/$id'
    | '/studio/c/$id/'
    | '/studio/c/$id/v/$variantId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/studio/new'
    | '/studio'
    | '/studio/c/$id'
    | '/studio/c/$id/v/$variantId'
  id:
    | '__root__'
    | '/'
    | '/studio'
    | '/studio/new'
    | '/studio/'
    | '/studio/c/$id'
    | '/studio/c/$id/'
    | '/studio/c/$id/v/$variantId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StudioRoute: typeof StudioRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/': {
      id: '/studio/'
      path: '/'
      fullPath: '/studio/'
      preLoaderRoute: typeof StudioIndexRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/new': {
      id: '/studio/new'
      path: '/new'
      fullPath: '/studio/new'
      preLoaderRoute: typeof StudioNewRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/c/$id': {
      id: '/studio/c/$id'
      path: '/c/$id'
      fullPath: '/studio/c/$id'
      preLoaderRoute: typeof StudioCIdRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/c/$id/': {
      id: '/studio/c/$id/'
      path: '/'
      fullPath: '/studio/c/$id/'
      preLoaderRoute: typeof StudioCIdIndexRouteImport
      parentRoute: typeof StudioCIdRoute
    }
    '/studio/c/$id/v/$variantId': {
      id: '/studio/c/$id/v/$variantId'
      path: '/v/$variantId'
      fullPath: '/studio/c/$id/v/$variantId'
      preLoaderRoute: typeof StudioCIdVVariantIdRouteImport
      parentRoute: typeof StudioCIdRoute
    }
  }
}

interface StudioCIdRouteChildren {
  StudioCIdIndexRoute: typeof StudioCIdIndexRoute
  StudioCIdVVariantIdRoute: typeof StudioCIdVVariantIdRoute
}

const StudioCIdRouteChildren: StudioCIdRouteChildren = {
  StudioCIdIndexRoute: StudioCIdIndexRoute,
  StudioCIdVVariantIdRoute: StudioCIdVVariantIdRoute,
}

const StudioCIdRouteWithChildren = StudioCIdRoute._addFileChildren(
  StudioCIdRouteChildren,
)

interface StudioRouteChildren {
  StudioNewRoute: typeof StudioNewRoute
  StudioIndexRoute: typeof StudioIndexRoute
  StudioCIdRoute: typeof StudioCIdRouteWithChildren
}

const StudioRouteChildren: StudioRouteChildren = {
  StudioNewRoute: StudioNewRoute,
  StudioIndexRoute: StudioIndexRoute,
  StudioCIdRoute: StudioCIdRouteWithChildren,
}

const StudioRouteWithChildren =
  StudioRoute._addFileChildren(StudioRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StudioRoute: StudioRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
